name: Docker Image CI

on:
  # workflow_dispatch
 push:
   branches: [ "feature/regex" ]
 pull_request:
   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        cd cat && docker build . -t pengxiangchen1992/cat:action10
        cd ../helloworld && docker build . -t pengxiangchen1992/helloworld:action10
        cd ../web-nginx && docker build . -t pengxiangchen1992/mynginx:action10
        
    - name: Upload the Docker image
      run: |
        docker login -u pengxiangchen ${{ secrets.DOCKER_USERNAME }} -p Love2755! ${{ secrets.DOCKER_PASSWORD }}
        docker push pengxiangchen1992/cat:action10
        docker push pengxiangchen1992/helloworld:action10
        docker push pengxiangchen1992/mynginx:action10

    - name: SSH to Remote Server and Run docker-compose
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 20.213.56.87
        username: pengxiangchen
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2020        
        script: |
          echo "Running command on remote server"
          cd ~/WK2_Docker
          git pull
          sudo docker-compose down
          sudo docker-compose up -d
          sudo docker-compose ps
      # uses: fifsky/ssh-action@master
      # with:
      #   command: |
      #     cd /tmp
      #     ls -a
      #   host: 20.213.125.197
      #   user: azureuser
      #   key: ${{ secrets.SSH_PRIVATE_KEY}}
